<a href="https://colab.research.google.com/github/ssuxmin/tmp/blob/main/chap_3_%EC%BC%80%EB%9D%BC%EC%8A%A4%EC%99%80_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_%EC%86%8C%EA%B0%9C(%EC%BD%94%EB%93%9C_%EC%97%B0%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 3.5.1 상수 텐서와 변수(p.121)

**(코드 3-1) 모두 1 또는 0인 텐서** 

In [1]:
import tensorflow as tf
x=tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [2]:
x=tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


**(코드 3-2) 랜덤 텐서**

In [3]:
x=tf.random.normal(shape=(3,1), mean=0, stddev=1,) 
# 평균이 0, 표준편차가 1인 정규분포에서 뽑은 랜덤한 값으로 만든 텐서
# np.random.normal(size=(3,1),loc=0., scale=1.) 와 같음!!!!!
print(x)

tf.Tensor(
[[-0.62870735]
 [-2.3548834 ]
 [-0.09732541]], shape=(3, 1), dtype=float32)


In [5]:
x=tf.random.uniform(shape=(3,1), minval=0, maxval=1.)
# 0과 1 사이의 균등분포에서 뽑은 랜덤한 값으로 만든 텐서
# np.random.normal(size=(3,1),low=0., high=1.) 와 같음!!!!!
print(x)

tf.Tensor(
[[0.08670056]
 [0.5701883 ]
 [0.90638554]], shape=(3, 1), dtype=float32)


**텐서플로 텐서는 상수!!   (값을 할당할 수 없음)** 

**(코드 3-3) 넘파이 배열에 값 할당하기**

In [6]:
import numpy as np
x= np.ones(shape=(2,2))
x[0,0]=0.

In [7]:
x

array([[0., 1.],
       [1., 1.]])

**(코드3-4) 텐서플로 텐서에 값을 할당 못하는 예제**

In [8]:
x= tf.ones(shape=(2,2))
x[0,0]=0.    # 텐서에는 값을 할당할 수 없기 때문에 에러 발생!

TypeError: ignored

**(코드3-5) 텐서플로 변수 만들기**

In [10]:
v=tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.1065823 ],
       [-0.97207433],
       [-0.6407829 ]], dtype=float32)>


**(코드3-6) 텐서플로 변수에 값 할당하기**

In [13]:
v.assign(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

**(코드3-7) 변수 일부에 값 할당하기**

In [14]:
v[0,0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

**(코드3-8) assign.add() 사용하기**

In [15]:
v.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

### 3.5.2 텐서 연산 : 텐서플로에서 수학 계산하기

****(코드3-9) 기본적인 수학 연산**

In [16]:
a = tf.ones((2, 2))
b = tf.square(a)      # 제곱
c = tf.sqrt(a)        # 제곱근
d = b + c             # 두 텐서 더함
e = tf.matmul(a, b)   # 두 텐서의 점곱 계산
e *= d                # 두 텐서를 곱함 

### 3.5.3 GradientTape API 다시 살펴보기(p.124)